# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ViewExercises' do

end

target 'ViewExercisesTests' do

end

platform :ios, '8.0'
use_frameworks!

pod 'SnapKit'